'use strict';

export const ContentList = [
	"roll6_tempura_crab", 
	"roll6_tuna_avocado",
	"nigiri6_amaebi", 
	"nigiri6_kanpachi_gold",
	"nigiri10_uni", 
	"roll8_salmon_garlic", 
	"roll8_salmon_guac", 
	"roll8_seared_salmon_ikura",
	"roll8_lobster_volcano",
	"spoon4_tako_paella",
	"roll8_vegan_asparagus",
	"nigiri6_hamachi_ginger",
	"nigiri4_otoro_double",
	"nigiri4_geoduck",
	"roll8_amberjack_tuna",
	"roll6_monkfish_bites",
	"handroll3_rainbow_matcha",
	"nigiri6_tuna_fluke",
	"roll8_rainbow_white",
	"roll8_crunchy_salmon",
	"roll8_hamachi_lotus",
	"spoon5_scallop",
];